const initialProfile = {
  budget: 50000,
  units: {
    Riflemen: 100,
    Sniper: 5,
    Medic: 25,
    AntiTank: 5,
    MachineGunner: 0,
    Battleship: 0,
    Destroyer: 0,
    Submarine: 0,
    Frigate: 0,
    Cruiser: 0,
    FighterJet: 0,
    Drone: 0,
    AttackHelicopter: 0,
    Bomber: 0,
    SatelliteSystems: 0,
    Robotics: 0,
    Biotechnology: 0,
    Nanotechnology: 0,
    FieldHospital: 0,
    AerialSupplyDrop: 0,
    EngineeringCorp: 0,
    MedicalEvacVehicle: 0,
    HumanIntel: 10,
    CyberIntel: 0,
    DroneSurveillanceUnit: 0,
  },
  profileStats: {
    level: 1,
    xp: 0,
    nextLevelXp: 500,
    totalBattles: 0,
    total_wins: 0,
    total_losses: 0,
    highestEnemyLevelDefeated: 0,
    firstVictory: false,
  },
};

module.exports = initialProfile;
